CompileFlags:
    Add: [
          -Wall,
          -Wextra,
          -fsanitize=undefined,
        # -Werror,
    ]
 
InlayHints:
    Enabled: Yes
    ParameterNames: Yes
    DeducedTypes: Yes

Diagnostics:
    UnusedIncludes: Strict
      #ClangTidy:
      #    Add: [
      #        clang-analyzer-*, 
      #        concurrency-*, 
      #        # misc-*, 
      #        performance-*,
      #        portability-*,
      #        # readability-*
      #    ]

---

If:
    PathMatch: [.*\.cc, .*\.hh, .*\.hpp, .*\.cpp]
CompileFlags:
    Add: [
        -std=c++2a,
        # -stdlib=libc++,
    ]
#Diagnostics:
  #    ClangTidy:
  #        Add: [
  #            boost-*, 
  #            cppcoreguidelines-*, 
  #            hicpp-*, 
  #            modernize-*, 
  #        ]


---

If:
    PathMatch: [.*\.c, .*\.h]
CompileFlags:
    Add: [
        -std=c11,
    ]
