CompileFlags:
    Add:
      [
        # -std=c89,
        # -stdlib=libc++,
        # -std=c++2a,
        -Wall,
        -Wextra,
        # -Werror,
      ]
    Compiler: clang
 
InlayHints:
  Enabled: Yes
  ParameterNames: Yes
  DeducedTypes: Yes
