CompileFlags:
    Add: [
        -Wall,
        -Wextra,
        # -Werror,
      ]
 
InlayHints:
  Enabled: Yes
  ParameterNames: Yes
  DeducedTypes: Yes

Diagnostics:
  UnusedIncludes: Strict

---

If:
  PathExclude: [.*\.c, .*\.h]
CompileFlags:
  Add: [
      # -std=c++2a,
      # -stdlib=libc++,
    ]

---

If:
  PathExclude: [.*\.cc, .*\.cpp, .*\.hpp]
CompileFlags:
  Add: [
    -std=c89,
  ]